# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78c880748f99afec68db9e64fbf9c3ba10f4cfeb19e6765565748dd3ae2506f2aea6ce38abb0915e873716a895e23ec8b077aa20bc488440fc6b006acb2c3f2

test:
  secret_key_base: 840b347767f95fa81718da554650fea65aa41c2ccb42d7c922595b4d1a2da2576c9038a15e2a8fcf7e12e5ad43727b690e1aec4ca63c71869c4a3b702cc0e489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
